package view;

import Utils.ConexaoSQLITE;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author hans
 */
public class Tela_Principal extends javax.swing.JFrame {
    // instanciar conexao com banco
    ConexaoSQLITE conexao = new ConexaoSQLITE();
    
    Tela_Usu u = new Tela_Usu();
    
    public Tela_Principal() {
        initComponents();
        conexao.conectar();
        
        // faz aparecer a tela de horários assim que inicia
        Tela_Hor h = new Tela_Hor();
        h.setVisible(true);
        desk.add(h);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desk = new javax.swing.JDesktopPane();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnHor = new javax.swing.JButton();
        btnCli = new javax.swing.JButton();
        btnSer = new javax.swing.JButton();
        btnUsu = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menAte = new javax.swing.JMenu();
        menCli = new javax.swing.JMenuItem();
        menHor = new javax.swing.JMenuItem();
        menSer = new javax.swing.JMenuItem();
        menU = new javax.swing.JMenu();
        menUsu = new javax.swing.JMenuItem();
        menRel = new javax.swing.JMenu();
        menRel_cli = new javax.swing.JMenuItem();
        menRel_hor = new javax.swing.JMenuItem();
        menRel_ser = new javax.swing.JMenuItem();
        menOpc = new javax.swing.JMenu();
        menAju = new javax.swing.JMenuItem();
        MenuItem_edit_hor = new javax.swing.JMenuItem();
        menSob = new javax.swing.JMenuItem();
        menS = new javax.swing.JMenu();
        menSai = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal - MEHSYS");
        setPreferredSize(new java.awt.Dimension(910, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblUsuario.setText("Usuário");

        lblData.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        lblData.setText("Data");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_gra.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel1.setText("v 1.02");

        btnHor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hor_ico2.png"))); // NOI18N
        btnHor.setToolTipText("Agendamentos");
        btnHor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorActionPerformed(evt);
            }
        });

        btnCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cli_ico2.png"))); // NOI18N
        btnCli.setToolTipText("clientes");
        btnCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliActionPerformed(evt);
            }
        });

        btnSer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ser_ico2.png"))); // NOI18N
        btnSer.setToolTipText("serviços");
        btnSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerActionPerformed(evt);
            }
        });

        btnUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usu_ico2.png"))); // NOI18N
        btnUsu.setToolTipText("usuários");
        btnUsu.setEnabled(false);
        btnUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuActionPerformed(evt);
            }
        });

        menAte.setText("Atendimentos");

        menCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cli_ico.png"))); // NOI18N
        menCli.setText("Clientes");
        menCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCliActionPerformed(evt);
            }
        });
        menAte.add(menCli);

        menHor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menHor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hor_ico.png"))); // NOI18N
        menHor.setText("Horários");
        menHor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menHorActionPerformed(evt);
            }
        });
        menAte.add(menHor);

        menSer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menSer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ser_ico.png"))); // NOI18N
        menSer.setText("Serviços");
        menSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSerActionPerformed(evt);
            }
        });
        menAte.add(menSer);

        jMenuBar1.add(menAte);

        menU.setText("Usuários");
        menU.setEnabled(false);

        menUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usu_ico.png"))); // NOI18N
        menUsu.setText("Usuários");
        menUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menUsuActionPerformed(evt);
            }
        });
        menU.add(menUsu);

        jMenuBar1.add(menU);

        menRel.setText("Relatórios");
        menRel.setEnabled(false);

        menRel_cli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menRel_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imp2.png"))); // NOI18N
        menRel_cli.setText("Clientes");
        menRel_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRel_cliActionPerformed(evt);
            }
        });
        menRel.add(menRel_cli);

        menRel_hor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menRel_hor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imp2.png"))); // NOI18N
        menRel_hor.setText("Horários");
        menRel_hor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRel_horActionPerformed(evt);
            }
        });
        menRel.add(menRel_hor);

        menRel_ser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menRel_ser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imp2.png"))); // NOI18N
        menRel_ser.setText("Serviços");
        menRel_ser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRel_serActionPerformed(evt);
            }
        });
        menRel.add(menRel_ser);

        jMenuBar1.add(menRel);

        menOpc.setText("Opções");

        menAju.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menAju.setText("Ajuda");
        menAju.setEnabled(false);
        menAju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAjuActionPerformed(evt);
            }
        });
        menOpc.add(menAju);

        MenuItem_edit_hor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuItem_edit_hor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/novo.png"))); // NOI18N
        MenuItem_edit_hor.setText("Atualizar horários");
        MenuItem_edit_hor.setEnabled(false);
        MenuItem_edit_hor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_edit_horActionPerformed(evt);
            }
        });
        menOpc.add(MenuItem_edit_hor);

        menSob.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menSob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sobre.png"))); // NOI18N
        menSob.setText("Sobre");
        menSob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSobActionPerformed(evt);
            }
        });
        menOpc.add(menSob);

        jMenuBar1.add(menOpc);

        menS.setText("Sair");
        menS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSActionPerformed(evt);
            }
        });

        menSai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menSai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sai_ico.png"))); // NOI18N
        menSai.setText("Sair");
        menSai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSaiActionPerformed(evt);
            }
        });
        menS.add(menSai);

        jMenuBar1.add(menS);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(desk, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addComponent(lblData)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCli))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUsu)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblUsuario)
                        .addGap(37, 37, 37)
                        .addComponent(lblData)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHor)
                            .addComponent(btnCli))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSer)
                            .addComponent(btnUsu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(desk)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(920, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSActionPerformed
  
    }//GEN-LAST:event_menSActionPerformed

    private void menSaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSaiActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que quer sair?", "Sair?", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            conexao.desconectar();
            System.exit(0);
        }
    }//GEN-LAST:event_menSaiActionPerformed

    private void menUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menUsuActionPerformed
        u.setVisible(true);
        desk.removeAll();
        desk.add(u);
        Tela_Usu.txtPes_usu.requestFocusInWindow();
    }//GEN-LAST:event_menUsuActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // as linhas a baixo substituem a lblData pela data atual do sistema
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.DEFAULT);
        lblData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void menCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCliActionPerformed
        Tela_Cli c = new Tela_Cli();
        c.setVisible(true);
        desk.removeAll();
        desk.add(c);
        Tela_Cli.txtPes_cli.requestFocusInWindow();
    }//GEN-LAST:event_menCliActionPerformed

    private void menHorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menHorActionPerformed
        Tela_Hor h = new Tela_Hor();
        h.setVisible(true);
        desk.removeAll();
        desk.add(h);
        Tela_Hor.txtPesC_hor.requestFocusInWindow();
    }//GEN-LAST:event_menHorActionPerformed

    private void menSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSerActionPerformed
        Tela_Ser s = new Tela_Ser();
        s.setVisible(true);
        desk.removeAll();
        desk.add(s);
        Tela_Ser.txtPes_ser.requestFocusInWindow();
    }//GEN-LAST:event_menSerActionPerformed

    private void menRel_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRel_cliActionPerformed
        // gerando relatório de clientes
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a emissão de relatório de todos os clientes do sistema?","Atenção!", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            // imprimindo relatório com jasperreport
            try {
                // imprimindo relatorios com jasperreportes
                JasperPrint print = JasperFillManager.fillReport("rel/rel_clientes.jasper", null, conexao.getConexao());
                // exibe o relatório
                JasperViewer.viewReport(print, false);
            } catch (JRException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_menRel_cliActionPerformed

    private void menRel_serActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRel_serActionPerformed
        // gerando relatório de serviços
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a emissão de relatório de todos os serviços do sistema?","Atenção!", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            // imprimindo relatório com jasperreport
            try {
                // imprimindo relatorios com jasperreportes
                JasperPrint print = JasperFillManager.fillReport("rel/rel_servicos.jasper", null, conexao.getConexao());
                // exibe o relatório
                JasperViewer.viewReport(print, false);
            } catch (JRException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_menRel_serActionPerformed

    private void menRel_horActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRel_horActionPerformed
        // gerando relatório de agendamentos
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a emissão de relatório de todos os agendamentos do sistema?","Atenção!", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            // imprimindo relatório com jasperreport
            try {
                // imprimindo relatorios com jasperreportes
                JasperPrint print = JasperFillManager.fillReport("rel/rel_horarios.jasper", null, conexao.getConexao());
                // exibe o relatório
                JasperViewer.viewReport(print, false);
            } catch (JRException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_menRel_horActionPerformed

    private void menSobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSobActionPerformed
        Tela_Sobre s = new Tela_Sobre();
        s.setVisible(true);
    }//GEN-LAST:event_menSobActionPerformed

    private void menAjuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAjuActionPerformed
        Tela_Ajuda a = new Tela_Ajuda();
        a.setVisible(true);
    }//GEN-LAST:event_menAjuActionPerformed

    private void btnHorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorActionPerformed
        Tela_Hor h = new Tela_Hor();
        h.setVisible(true);
        desk.removeAll();
        desk.add(h);
        Tela_Hor.txtPesC_hor.requestFocusInWindow();
    }//GEN-LAST:event_btnHorActionPerformed

    private void btnCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliActionPerformed
        Tela_Cli c = new Tela_Cli();
        c.setVisible(true);
        desk.removeAll();
        desk.add(c);
        Tela_Cli.txtPes_cli.requestFocusInWindow();
    }//GEN-LAST:event_btnCliActionPerformed

    private void btnSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerActionPerformed
        Tela_Ser s = new Tela_Ser();
        s.setVisible(true);
        desk.removeAll();
        desk.add(s);
        Tela_Ser.txtPes_ser.requestFocusInWindow();
    }//GEN-LAST:event_btnSerActionPerformed

    private void btnUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuActionPerformed
        u.setVisible(true);
        desk.removeAll();
        desk.add(u);
        Tela_Usu.txtPes_usu.requestFocusInWindow();
    }//GEN-LAST:event_btnUsuActionPerformed

    private void MenuItem_edit_horActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_edit_horActionPerformed
        Tela_editHor teh = new Tela_editHor();
        teh.setVisible(true);
    }//GEN-LAST:event_MenuItem_edit_horActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuItem MenuItem_edit_hor;
    private javax.swing.JButton btnCli;
    private javax.swing.JButton btnHor;
    private javax.swing.JButton btnSer;
    public static javax.swing.JButton btnUsu;
    public static javax.swing.JDesktopPane desk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem menAju;
    private javax.swing.JMenu menAte;
    private javax.swing.JMenuItem menCli;
    private javax.swing.JMenuItem menHor;
    private javax.swing.JMenu menOpc;
    public static javax.swing.JMenu menRel;
    private javax.swing.JMenuItem menRel_cli;
    private javax.swing.JMenuItem menRel_hor;
    private javax.swing.JMenuItem menRel_ser;
    private javax.swing.JMenu menS;
    private javax.swing.JMenuItem menSai;
    private javax.swing.JMenuItem menSer;
    private javax.swing.JMenuItem menSob;
    public static javax.swing.JMenu menU;
    private javax.swing.JMenuItem menUsu;
    // End of variables declaration//GEN-END:variables
}
