/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Utils.ConexaoSQLITE;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author hans
 */
public class Tela_editHor extends javax.swing.JFrame {

    ConexaoSQLITE conexao = new ConexaoSQLITE();
    PreparedStatement pst = null;
    ResultSet rs = null;

    public Tela_editHor() {
        initComponents();
        conexao.conectar();
        popula_tabela();
        txt_horario.setFocusable(true);
    }

    private void limpar() {
        txt_horario.setText(null);
    }

    // metodo para adicionar novo usuario
    public void adicionar() {
        conexao.conectar();
        String sql = "insert into horarios(horario) values(?)";
        try {
            pst = conexao.criarPreparedStatement(sql);
            pst.setString(1, txt_horario.getText());
            System.out.println(txt_horario.getText());

            // validação dos campos obrigatorios
            if (txt_horario.getText().isEmpty() || txt_horario.getText().trim().length() < 5) {
                JOptionPane.showMessageDialog(null, "Preencha o campo com algum horário!");
            } else if ((Integer.parseInt(txt_horario.getText().substring(0, 2)) >= 24)
                    || (Integer.parseInt(txt_horario.getText().substring(3, 5)) >= 60)) {
                JOptionPane.showMessageDialog(null, "Horário Inválido!");
            } else {

                // a linha abaixo atualiza a tabela usuarios com os dados do formu
                // a estrutura abaixo é usada para confirmar a insersão de dados
                int adicionado = pst.executeUpdate();  // retorna 1 ou 0
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Usuário adicionado com sucesso!");
                    this.limpar();
                    this.popula_tabela();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // metodo para setar campos do formulario com dados da tabela
    private void setar_campos() {
        int setar = tabela_hor.getSelectedRow();
        txt_horario.setText(tabela_hor.getModel().getValueAt(setar, 0).toString());

        // a linha abaixo desabilita btn adicionar
        btn_add_hor.setEnabled(false);
    }

    // metodo para remover usuário do banco de dados
    private void remover() {
        if (!txt_horario.getText().isEmpty()) {
            int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover este horário?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (confirma == JOptionPane.YES_OPTION) {
                String sql = "delete from horarios where horario=?";
                try {
                    pst = conexao.criarPreparedStatement(sql);
                    pst.setString(1, txt_horario.getText());
                    int apagado = pst.executeUpdate();
                    if (apagado > 0) {
                        //JOptionPane.showMessageDialog(null, "Horário removido com sucesso!");
                        this.limpar();
                        this.popula_tabela();
                        this.btn_add_hor.setEnabled(true);
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um horário para poder excluir!");
        }
    }

// método para consultar usuarios no bd
    private void popula_tabela() {
        String sql = "select * from horarios";
        try {
            pst = conexao.criarPreparedStatement(sql);
            // passando o conteudo da caixa de pesquisa para o ?
            // atençao ao % que é a continuação da string sql
            //pst.setString(1, "");
            rs = pst.executeQuery();
            // a linha abaixo usa a biblioteca rs2xml.jar
            tabela_hor.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_horario = new javax.swing.JFormattedTextField();
        btn_clear = new javax.swing.JButton();
        btn_add_hor = new javax.swing.JButton();
        btn_delete_hor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_hor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edição de Horários Disponíveis - Mehsys");
        setMinimumSize(new java.awt.Dimension(322, 400));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar Horários de Trabalho"));

        jLabel1.setText("Horário de Trabalho:");

        try {
            txt_horario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_horario.setToolTipText("Digitar horário");
        txt_horario.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txt_horario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_horarioActionPerformed(evt);
            }
        });

        btn_clear.setText("Limpar");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_add_hor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nov_blue.png"))); // NOI18N
        btn_add_hor.setText("Adicionar");
        btn_add_hor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_horActionPerformed(evt);
            }
        });

        btn_delete_hor.setForeground(new java.awt.Color(204, 0, 0));
        btn_delete_hor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/del_blue.png"))); // NOI18N
        btn_delete_hor.setText("Deletar");
        btn_delete_hor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_horActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_add_hor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_clear))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_delete_hor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_hor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete_hor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tabela_hor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Horário"
            }
        ));
        tabela_hor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_horMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_hor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Editar Horários de Trabalho");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_horarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_horarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_horarioActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tabela_horMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_horMouseClicked
        setar_campos();
    }//GEN-LAST:event_tabela_horMouseClicked

    private void btn_add_horActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_horActionPerformed
        adicionar();
    }//GEN-LAST:event_btn_add_horActionPerformed

    private void btn_delete_horActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_horActionPerformed
        remover();
    }//GEN-LAST:event_btn_delete_horActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        limpar();
    }//GEN-LAST:event_btn_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_editHor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_editHor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_editHor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_editHor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_editHor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_hor;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete_hor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_hor;
    private javax.swing.JFormattedTextField txt_horario;
    // End of variables declaration//GEN-END:variables
}
